****--WRITE A QUERY FOR SALARY CATEGORY***

SELECT first_name,salary,
 CASE WHEN salary>=15000 THEN 'HIGH'
      WHEN salary>= 8000 THEN 'MEDIUM'
      ELSE 'LOW'
 END AS salary_category
 FROM HR.EMPLOYEES

-- &&&&---EXP > 12 IS SENIOR AND EXP>5 IS MID LEVEL ELSE JUNIOR


SELECT EMPLOYEE_ID,FIRST_NAME,
 CASE WHEN ((SYSDATE-HIRE_DATE)/365)>=12 THEN 'SENIOR'
    WHEN ((SYSDATE-HIRE_DATE))/365>5  THEN 'MID LEVEL'
    ELSE 'JUNIOR'
 END
FROM hr.EMPLOYEES


--WRITE A QUERY TO GIVE HIKE BASED O SALARY--


SELECT EMPLOYEE_ID,FIRST_NAME,SALARY,
CASE
    WHEN SALARY>=15000 THEN SALARY+SALARY*0.40
    WHEN SALARY>8000 THEN SALARY+SALARY*0.20
    ELSE SALARY+SALARY*0.10
END AS BONUS 
FROM HR.EMPLOYEES