SET SERVEROUTPUT ON;
DECLARE
  v_salary HR.EMPLOYEES.SALARY%TYPE;
BEGIN
    SELECT SALARY INTO v_salary FROM HR.EMPLOYEES 
    WHERE EMPLOYEE_ID=110;
    IF v_salary>10000 THEN
    DBMS_OUTPUT.PUT_LINE('HIGH SALARY EMPLOYEE');
    ELSE 
    DBMS_OUTPUT.PUT_LINE('LOW SALARY EMPLOYEE');

    END IF;
END;


SET SERVEROUTPUT ON;
DECLARE
  v_job hr.EMPLOYEES.JOB_ID%TYPE;
BEGIN
    SELECT JOB_ID INTO v_job FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=104;
    IF v_job LIKE 'IT%' THEN
    DBMS_OUTPUT.PUT_LINE('IT DEPARTMENT');
    ELSIF v_job LIKE 'FI%' THEN
    DBMS_OUTPUT.PUT_LINE('FINANCE DEPARTMENT');
    ELSIF v_job LIKE 'SA%' THEN
    DBMS_OUTPUT.PUT_LINE('SALES DEPARTMENT');
    ELSE
    DBMS_OUTPUT.PUT_LINE('OTHER DEPARTMENT');
    END IF;
END;


SET SERVEROUTPUT ON
DECLARE
 v_employee_id hr.EMPLOYEES.EMPLOYEE_ID%TYPE;
 v_first_name hr.EMPLOYEES.FIRST_NAME%TYPE;
 v_last_name hr.EMPLOYEES.LAST_NAME%TYPE;
 v_email hr.EMPLOYEES.EMAIL%TYPE;
 v_salary hr.EMPLOYEES.SALARY%TYPE;
 v_department_id hr.EMPLOYEES.DEPARTMENT_ID%TYPE;
BEGIN
    SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,SALARY,DEPARTMENT_ID INTO
    v_employee_id,v_first_name,v_last_name,v_email,v_salary,v_department_id FROM HR.EMPLOYEES
    WHERE EMPLOYEE_ID= 101;
DBMS_OUTPUT.PUT_LINE('Employee Name : ' || v_first_name||' ' || v_last_name);
DBMS_OUTPUT.PUT_LINE('Email Id : ' ||' '|| v_email);
DBMS_OUTPUT.PUT_LINE('Department Id: ' ||' '|| v_department_id);

IF v_salary>= 5000 THEN
DBMS_OUTPUT.PUT_LINE('STATUS: High Salary Employee');
ELSE
DBMS_OUTPUT.PUT_LINE('STATUS: Low Salary Employee');
END IF;

END;

