SELECT FIRST_NAME,DEPARTMENT_ID,
DECODE(DEPARTMENT_ID,30,'ADMISTRATION',50,'MARKETING',90,'PURCHASING','OTHER DEPT')
AS DEPT_NAME FROM HR.EMPLOYEES


--WRITE A QUERY TO INCREMENT SALRY BASED ON DEPATMENT WISE--

SELECT FIRST_NAME,DEPARTMENT_ID,SALARY,
DECODE(DEPARTMENT_ID,30,SALARY+SALARY*0.20,50,SALARY+SALARY*0.30,90,SALARY+SALARY*0.40,SALARY+SALARY*0.10)
AS BONUS FROM HR.EMPLOYEES