CREATE TABLE EMP_DEMO(EMP_ID NUMBER,EMP_NAME VARCHAR2(20),DEPT_ID NUMBER,SALARY NUMBER);

INSERT INTO EMP_DEMO VALUES(1,'A',10,2000);
INSERT INTO EMP_DEMO VALUES(2,'B',10,3000);
INSERT INTO EMP_DEMO VALUES(3,'C',10,5000);
INSERT INTO EMP_DEMO VALUES(4,'D',20,7000);
INSERT INTO EMP_DEMO VALUES(5,'E',20,5000);
INSERT INTO EMP_DEMO VALUES(6,'F',20,6000);
 
SELECT * FROM EMP_DEMO

SELECT EMP_ID,SALARY,LEAD(SALARY)OVER(ORDER BY EMP_ID) AS LEAD_VALUE FROM EMP_DEMO

SELECT EMP_ID,SALARY,LEAD(SALARY,2)OVER(ORDER BY EMP_ID) AS LEAD_VALUE_2 FROM EMP_DEMO

SELECT EMP_ID,SALARY,LAG(SALARY)OVER(ORDER BY EMP_ID) AS LAG_VALUE FROM EMP_DEMO

SELECT EMP_ID,SALARY,LAG(SALARY,2)OVER(ORDER BY EMP_ID) AS LAG_VALUE_2 FROM EMP_DEMO


SELECT EMP_ID,DEPT_ID,SALARY,LEAD(SALARY)OVER(PARTITION BY DEPT_ID ORDER BY EMP_ID) AS LEAD_VALUE_DEPARTMANT FROM EMP_DEMO

SELECT EMP_ID,DEPT_ID,SALARY,LEAD(SALARY,2)OVER(PARTITION BY DEPT_ID ORDER BY EMP_ID) AS LEAD_VALUE_DEPARTMANT FROM EMP_DEMO.

SELECT EMP_ID,DEPT_ID,SALARY,LAG(SALARY)OVER(PARTITION BY DEPT_ID ORDER BY EMP_ID) AS LAG_VALUE_DEPARTMANT FROM EMP_DEMO

SELECT EMP_ID,DEPT_ID,SALARY,LAG(SALARY,2)OVER(PARTITION BY DEPT_ID ORDER BY EMP_ID) AS LAG_VALUE_DEPARTMANT FROM EMP_DEMO
